version: '3.8'

services:
  db:
    image: postgres:15
    container_name: zeron_crm_db
    restart: always
    environment:
      POSTGRES_USER: zeron_user
      POSTGRES_PASSWORD: zeron_password
      POSTGRES_DB: zeron_crm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
